require 'base64'

hsh = {
    "shipTrackEventCode": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDJQAAAAAAAADIwwlPkNWcLqCECuHW/q1+PUnePP2+yZd+tM+G/3eQLTa4pm3/",
    "orderId": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDLwAAAAAAAACliJgunHdR+pd/CgMHLNn5hGnZNaU9a8Nvm3cqfnMJAj1lOrPvYRsB4fr5rCGTag\u003d\u003d",
    "carrierType": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDHgAAAAAAAAAJa7vOGg02YH+IwiTvSmEb/wHTVN2C+dsOPvjKwRs\u003d",
    "isEeylops": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDIAAAAAAAAAANyd3z+PT65gxAQfQrqgHfDgN/KEK40AQTFee51zOTzQ\u003d\u003d",
    "eventType": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDOwAAAAAAAACopq6y5Xz9d67FF1RMAvI/GytSJiHPz962uPoUxMAeuHKiVJPnRTBMRm9wyxqDm1cw83RJtb6vMSe/2A\u003d\u003d",
    "orderingShipmentIds": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDKgAAAAAAAAB01j0N9nPW7RG8rzlUQRRr1iYuHzHfjgC89R1iApLU0ttBlKPT8iGJJtk\u003d",
    "fulfillmentShipmentId": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDKgAAAAAAAAC3tt2pBxFSwrAoCI5nDV2QoBanp8kJIJgK5KHef+IDlJhQs+kFJFyqGcw\u003d",
    "marketplaceId": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDKQAAAAAAAACvPLWsKL1NwyHVnhTQNRgq3fXN+B8U2fTtqyihjhdtCE+REL4AJ7VuIA\u003d\u003d",
    "countOfShipmentsInTheLargestOrder": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDHQAAAAAAAACQUk2nbLsm3MhI8Xh85tJe00t6IYUPJQUZLSPTWg\u003d\u003d",
    "customerId": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDKgAAAAAAAACP1I2bQH/uRlMLQ2Hdf5CuNHvmuIy15j1S7RKuSKQWtlO6K3KowtCHh+U\u003d",
    "numberOfShipmentItemEntitiesInTheLargestOrder": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDHQAAAAAAAAAUJqA3GaEfSdBdXx4VBo5BH6/0cI3YbKaJhmTlBQ\u003d\u003d",
    "orderIds": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDLwAAAAAAAABy03PX/xrZ/OGRMXUdlY6BbHv9g4zm1n6Cny//SKWjJk7zs5ppSOpbM3ZDEBwAnw\u003d\u003d",
    "trackingId": "AAAAAAAAAQCbDPbBGLKkOSFtdqHTVqrDLAAAAAAAAABf8bEht0sbOG70uO1XeMAlHjP5xEgkDCux36QCYinZYBrfUbbbQFL6PKLhWQ\u003d\u003d"
}

hsh.each { |k,v| puts k,Base64.decode64(v) }
